locations:
    rename: [530, 880]
    next: [980, 280]
    keyboard_ok: [933, 1085]
    rename_ok: [540, 1050]
    close_calcy_dialog: [880, 1160]
    edit_box: [90, 1090] # only used with --touch-paste
    paste: [483, 1092] # only used with --touch-paste
    favorite_button: [970, 160]
    favorite_button_box: [960, 142, 1001, 180]
    pokemon_menu_button: [940, 1700]
    appraise_button: [940, 1315]
    continue_appraisal: [540, 1100]
    calcy_appraisal_save_button: [880, 800]
    dismiss_calcy: [540, 1170]
    appraisal_box: [45, 1594, 1032, 1792]

waits:
    next: 0.5
    rename: 0.7
    rename_ok: 1.4
    pokemon_menu_button: 0.6
    appraise_button: 1
    calcy_appraisal_save_button: 5 #4
    continue_appraisal: 0.03

blacklist:
    -

actions:
    # Uncomment this and comment everything else to NOT rename any pokemon, just scan for adding to history
    # - conditions:
    #     success: true
    # - conditions:
    #     success: false

    # Failed scans get renamed for later verification
    - conditions:
        success: false
      actions:
        rename: "! Failed"

    # Renames Unowns with prefix
    - conditions:
        name__in:
          - Unown
      actions:
        rename-prefix: "‽ "

    # Renames Spindas with prefix
    - conditions:
        name__in:
          - Spinda
      actions:
        rename-prefix: "+ "

    # Legendary/ExRaid/Mythical/Good get renamed with custom prefix
    - conditions:
        name__in:
          - Mewtwo
          - Deoxys Normal
          - Giratina Altered
          - Celebi
          - Articuno
          - Zapdos
          - Moltres
          - Raikou
          - Gengar
          - Entei
          - Suicune
          - Ho-Oh
          - Lugia
          - Regirock
          - Regice
          - Registeel
          - Latias
          - Latios
          - Kyogre
          - Groudon
          - Rayquaza
          - Absol
          - Shedinja
      actions:
        rename-prefix: "»"

    # Renames hundos before everything else
    - conditions:
        iv__eq: 100
      actions:
        rename-calcy:

    # # Potential IV0 get appraised or renamed for later verification
    # - conditions:
    #     iv:
    #     iv_min__eq: 0
    #     appraised: false
    #   actions:
    #     appraise:
    #     rename: "! Verify"

    # Potential IV100 get appraised or renamed for later verification
    - conditions:
        iv:
        iv_max__eq: 100
        appraised: false
      actions:
        # appraise:
        rename: "! Verify"

    # For trading as well, but keeps stats visible because they may come useful in a pinch
    - conditions:
        name__in:
          - Tyranitar
          - Dragonite
          - Snorlax
          - Machamp
          - Blissey
          - Shinx
          - Salamence
          - Chansey
          - Golem Normal
          - Flareon
          - Vaporeon
          - Exeggutor
          - Exeggutor Alolan
      actions:
        rename-prefix: "★ "

    # Renames luckyegg evo pokemons (except hundos)
    - conditions:
        name__in:
          - Pidgey
          - Weedle
          - Whishmur
          - Wurmple
          - Caterpie
      actions:
        rename-prefix: "‰ "

    # Renames everything between (max) IV95 and 100 with a prefix,
    # for easily transfering shitty IV95-100 common pokemons afterwards
    - conditions:
        iv_max__ge: 95
      actions:
        rename-prefix: "∞ "

    # For Trading for candy like whatever
    - conditions:
        name__in:
          - Larvitar
          - Pupitar
          - Bagon
          - Shelgon
          - Beldum
          - Metang
          - Ralts
          - Machop
          - Machoke
          - Pineco
          - Lickitung
          - Slakoth
          - Dratini
      actions:
        rename-prefix: "• "

    # Skips everything else below IV95
    - conditions:
        iv_max__lt: 95


    # Renames anything else that doesn't matches any rule above
    #  which, in theory, shouldn't happen, so it adds a prefix to fix the rules
    - actions:
        rename-prefix: "¿ "


iv_regexes:
    - ^.+     (?P<iv>\d+)$
    - ^.+     (?P<iv_min>\d+)\-(?P<iv_max>\d+)$



###################
## Sorting Table ##
###################

## Order in which Pokemon displays pokémons when sorting by A-Z
# - `꩜ ` (the special @, does not exist on Gboard)
# - `$`
# - `%`
# - `&`
# - `*`
# - `@`
# - `,`
# - `.`
# - `?`
# - `_`
# - `¡` (alongside `!`)
# - `¿` (alongside `?`)
# - `“` (alongside `"`)
# - `›` (alongside `'`)
# - `‽` (alongside `?`)
# - `+`
# - `⁺` (superscript plus, does not exist on Gboard)
# - `»` (alongside `"`)
# - `÷`
# - `×`
# - `∅` (alingside `0`)
# - `≈` (alongside `=`)
# - `↑` (alingside `^`)
# - `→` (alingside `^`)
# - `↓` (alingside `^`)
# - `←` (alingside `^`)
# - `·` (alongside `-`)
# - `†` (alongside `*`)
# - `‡` (alongside `*`)
# - `•`
# - `★` (alongside `*`)
# - `♠` (alongside `•`)
# - `♦` (alongside `•`)
# - `♣` (alongside `•`)
# - `♥` (alongside `•`)
# - `✓`
# - `‰`
# - `∞` (alongside `=`)