locations:
    rename: [530, 880]
    next: [980, 280]
    keyboard_ok: [933, 1085]
    rename_ok: [540, 1050]
    close_calcy_dialog: [880, 1160]
    edit_box: [90, 1090] # only used with --touch-paste
    paste: [483, 1092] # only used with --touch-paste
    favorite_button: [970, 160]
    favorite_button_box: [960, 142, 1001, 180]
    pokemon_menu_button: [940, 1700]
    appraise_button: [940, 1315]
    continue_appraisal: [540, 1100]
    calcy_appraisal_save_button: [880, 920]
    dismiss_calcy: [540, 1170]
    appraisal_box: [45, 1594, 1032, 1792]

waits:
    next: 0.7
    rename: 1
    rename_ok: 1.5
    pokemon_menu_button: 0.6
    appraise_button: 1
    calcy_appraisal_save_button: 8 #4
    continue_appraisal: 0.05

blacklist:
    -

actions:
    - conditions:
        success: false
      actions:
        rename: "!FAILED"
    - conditions:
        name__in:
          - Unown
      actions:
        rename: "‽Unown"
    - conditions:
        iv:
        iv_min__eq: 0
        appraised: false
      actions:
        # rename-calcy:
        appraise:
    - conditions:
        iv:
        iv_max__eq: 100
        appraised: false
      actions:
        # rename-calcy:
        appraise:
    # Legendary/ExRaid/Mythical/Good
    - conditions:
        name__in:
          - Mewtwo
          - Deoxys Normal
          - Giratina Altered
          - Celebi
          - Articuno
          - Zapdos
          - Moltres
          - Raikou
          - Gengar
          - Entei
          - Suicune
          - Ho-oh
          - Lugia
          - Regirock
          - Regice
          - Registeel
          - Latias
          - Latios
          - Kyogre
          - Groudon
          - Rayquaza
          - Absol
      actions:
        rename-calcy:
    - conditions:
        iv_max__ge: 60
        cp__ge: 2200
      actions:
        rename-calcy:
    # For Trade Candy
    - conditions:
        name__in:
          - Larvitar
          - Pupitar
          - Bagon
          - Shelgon
          - Beldum
          - Metang
          - Ralts
          - Machop
          - Pineco
      actions:
        rename: "• TRADE"
    # For trade with others
    - conditions:
        name__in:
          - Tyranitar
          - Dratini
          - Dragonite
          - Snorlax
      actions:
        rename-prefix: "•"
    - conditions:
        iv_max__ge: 90
        cp__ge: 2000
      actions:
        rename-calcy:
    - conditions:
        iv_max__lt: 90
    - actions:
        rename-calcy: # Rename normally

iv_regexes:
    - ^.+     (?P<iv>\d+)$
    - ^.+     (?P<iv_min>\d+)\-(?P<iv_max>\d+)$