- Mewtwo
- Mewtwo Armored
- Palkia
- Deoxys Normal
- Deoxys Attack
- Deoxys Defense
- Deoxys Speed
- Giratina Altered
- Giratina Origin
- Articuno
- Zapdos
- Moltres
- Raikou
- Entei
- Suicune
- Ho-Oh
- Lugia
- Regirock
- Regice
- Registeel
- Latias
- Latios
- Kyogre
- Groudon
- Rayquaza
- Cresselia
- Heatran
- Dialga
- Uxie
- Mesprit
- Azelf