## DOESNT WORK

# Locations for Google Pixel 1080x2400
# Use a nonevolved non-lucky poke (with three buttons) to calibrate calcy
# Check that it's working properly and it grabs the moves on lucky evolved pokemons

rename: [530, 880]
next: [980, 550]
rename_ok: [540, 1250]
close_calcy_dialog: [935, 1570]
edit_box: [90, 1090] # only used with --touch-paste
paste: [483, 1092] # only used with --touch-paste
favorite_button: [970, 160]
favorite_button_box: [960, 142, 1001, 180]
pokemon_menu_button: [940, 2175]
appraise_button: [940, 1780]
continue_appraisal: [540, 1375]
calcy_appraisal_save_button: [870, 870]
dismiss_calcy: [540, 1570]
appraisal_box: [60, 2080, 1030, 2260]
