## This is the most recent list of baby pokemon
# Last update: 2019-02-09
- Pichu
- Togepi
- Igglybuff
- Cleffa
- Elekid
- Smoochum
- Magby
- Budew
- Wynaut
- Tyrogue
- Azurill
- Munchlax
- Riolu
- Shinx
- Mantyke
- Chingling
- Happiny
- Bonsly
