- Larvitar
- Pupitar

- Dratini
- Dragonair

- Chansey

- Bagon
- Shelgon

- Beldum
- Metang

- Ralts
- Kirlia

- Machop
- Machoke

- Slakoth
- Vigoroth

- Marowak Alolan
- Mawile
- Absol
- Porygon
- Lickitung
- Pineco
- Trapinch

## You can delete pokemons above, but most
## people would agree that those are tradeable

## Add your own below:
- Cranidos
- Shieldon

# - Charmander
# - Pidgey
# - Finneon
# - Clamperl
